site_name: Yushu Docs
site_url: https://wuyushu514.github.io/
site_author: wuyushu514
site_description: a short description of your website

nav:
  - Windchill - ChangeOrder: windchill_changeOrder.md
  - Windchill - DOC: windchill_doc.md
  - Windchill - Workfolw: windchill_workflow.md
  - Java - temp: java_temp.md
theme:
  features:
    - content.code.copy
  name: material
  highlightjs: true
  hljs_languages:
    - yaml