site_name: Yushu Docs
site_url: https://wuyushu514.github.io/
site_author: wuyushu514
site_description: a short description of your website

nav:
  - Windchill - EC: windchill_ec.md
  - Windchill - DOC: windchill_doc.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml